### PR TITLE
feat: added missing readme.md file with contribution instruction

### PR DESCRIPTION
**Pull request by YuriScarbaci**

### CODE REVIEW

**Review by cabarius — APPROVED** [review]
awesome - thanks for doing this Yuri

**Comment by YuriScarbaci** [comment]
No problem, I missed an image path and I didn't expect you to merge this so fast, just created another PR with the fix

I would like to add https://www.conventionalcommits.org/en/v1.0.0/ to this so you can automatically generate a changelog of your changes just by following the convention `feat: ...` for new features `fix: ...` for bug fixes and `feat!: ...` / `fix!: ...` for new features/fixes that requires additional steps on the player (starting a new campaign?)

to do that this repository will require the `node/npm` stack (I can take care of adding it and creating the script for you to easly publish the changelog)

should I go ahead and do it or is it something you are not interested in?

Also, if you can share some documentation/tutorial I would love to star contribuiting on features in this but I have literally no idea how to start on unity modding and even less on this repository per se...

Any link you can share to help me start out?

**Comment by YuriScarbaci** [comment]
@cabarius

**Comment by YuriScarbaci** [comment]
I just realized you already had https://github.com/cabarius/ToyBox/tree/master/ToyBox which is a mix of changelog and readme in a txt file

I took the liberty of adding the instructions and reference on how to contribuite to the readme in my other PR

**Pull request merged**
