### PR TITLE
Truinto

### PR DESCRIPTION
**Pull request by Truinto**
So, I am quite sure that all blueprints are loaded on game start. No need to iterate through all blueprints by guid over and over. Check out ToyBox/classes/MainUI/BlueprintLoader.cs

[ToyBox] calling BlueprintLoader.Load
[ToyBox] loaded 162638 blueprints in 17 milliseconds
[ToyBox] success got 162638 bluerints

----------

Added enchantment editor. Not 100% done, but everything seems to work.

### CODE REVIEW

**Review by cabarius — APPROVED** [review]

**Comment by cabarius** [comment]
This looks awesome.  Thank you so much ^_^

**Comment by ArcaneTrixter** [comment]
I've swapped this back from being the mainline way of accessing blueprints because some users have reported crashing Toybox on any search (including the first one) on initial blueprint load in ```var filtered = blueprints.Where((bp) => bp.GetType().IsKindOf(type)).ToList();``` in BlueprintExtensions.cs:BlueprintsOfType() line 75.

**Comment by ArcaneTrixter** [comment]
For what it's worth, it worked for me and saw great reductions in load times, so I'd like to get this to be the default mechanism, just need to make sure users aren't crashing.

**Comment by Truinto** [comment]
I don't quite get how the original method never returned null, since there were path it could return null, but it never did.
So in short, I think all needed it to make sure GetBlueprints() doesn't return null, or inserted a check for null.

**Pull request merged**
